### PR TITLE
Feature/landing page

### PR DESCRIPTION
**Pull request by ThabisoMagwaza**
Hey guys, I've added the landing page to the game. I've also added some persistence using the browser's local storage. Players can just press 'new snake' when they die and continue playing.

### CODE REVIEW

**Review by callummdunne — APPROVED** [review]
Looks super cool well done

**Comment by ThabisoMagwaza** [comment]
> Looks super cool well done

Can I go ahead and merge this?

**Review by WrightKD — CHANGES_REQUESTED** [review]
Can you try and fix these issues : 

ERROR 5532 --- [boundChannel-13] .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method
org.springframework.messaging.converter.MessageConversionException: Could not write JSON: Index 7 out of bounds for length 7 (through reference chain: com.levelUp.multiplayerSnake.models.UpdatePayload["snakes"]->java.util.ArrayList[0]->com.levelUp.multiplayerSnake.models.Snake["snakeSegments"]->java.util.ArrayList[7]);

Also add some validation to the username so that it can't be empty/null/blank.

**Comment by keanutex** [comment]
> > Looks super cool well done
> 
> Can I go ahead and merge this?

**Comment by keanutex** [comment]
Yeah go ahead and merge

**Comment by ThabisoMagwaza** [comment]
> Can you try and fix these issues :
> 
> ERROR 5532 --- [boundChannel-13] .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method
> org.springframework.messaging.converter.MessageConversionException: Could not write JSON: Index 7 out of bounds for length 7 (through reference chain: com.levelUp.multiplayerSnake.models.UpdatePayload["snakes"]->java.util.ArrayList[0]->com.levelUp.multiplayerSnake.models.Snake["snakeSegments"]->java.util.ArrayList[7]);
> 
> Also add some validation to the username so that it can't be empty/null/blank.

I'll do this on my next commit, I just wanted the current page to be on the developer branch so that we can all start working with it.

**Pull request merged**
